IsEnabled: 'true'
includedItems:
- ITEM_ID_MAGIC_EGG
- ITEM_ID_ANTIMATTER_DUST
- ITEM_ID_COMET_DUST
- ITEM_ID_MUTATED_SEED
- ITEM_ID_LEGEN
- ITEM_ID_DARY
- ITEM_ID_PEBBLES_BLOCK
- ITEM_ID_DECORATIVE_SHRINE
- ITEM_ID_STONE_BLOCK
excludedItems:
- ITEM_ID_FIST
- ITEM_ID_WRENCH
