type:
  0: DEFAULT
  1: SUNSET
  2: NIGHT
  3: DESERT
  4: SUNNY
  5: RAINY_CITY
  6: HARVEST
  7: MARS
  8: SPOOKY
  9: MAW
  10: BLANK
  11: SNOWY
  12: GROWCH
  13: GROWCH_HAPPY
  14: UNDERSEA
  15: WARP
  16: COMET
  17: COMET2
  18: PARTY
  19: PINEAPPLE
  20: SNOWY_NIGHT
  21: SPRING
  22: WOLF
  23: NOT_INITIALIZED
  24: PURPLE_HAZE
  25: FIRE_HAZE
  26: GREEN_HAZE
  27: AQUA_HAZE
  28: CUSTOM_HAZE
  29: CUSTOM_ITEMS
  30: PAGODA
  31: APOCALYPSE
  32: JUNGLE
  33: BALLOON_WARZ
  34: BACKGROUND
  35: AUTUMN
  36: HEART
  37: STPATRICKS
  38: ICE_AGE
  39: VOLCANO
  40: FLOATING_ISLANDS
  41: MASCOT
  42: DIGITAL_RAIN
  43: MONOCHROME
  44: TREASURE
  45: SURGERY
  46: BOUNTIFUL
  47: METEOR
  48: STARS
  49: ASCENDED
  50: DESTROYED
  51: GROWTOPIA_SIGN
  52: DUNGEON
  53: LEGENDARY_CITY
  54: BLOOD_DRAGON
  55: POP_CITY
  56: ANZU
  57: TMNT_CITY
  58: RAD_CITY
  59: PLAZA
  60: NEBULA
  61: PROTOSTAR
  62: DARK_MOUNTAINS
  63: AC15
  64: MOUNT_GROWMORE
  65: CRACK_IN_REALITY
  66: LNY_NIAN
  67: RAYMAN_LOCK
  68: STEAMPUNK
  69: REALM_OF_SPIRITS
  70: BLACK_HOLE
  71: GEMS
  72: HOLIDAY_HAVEN
  73: FENYX_LOCK
  74: ENCHANTED_LOCK
  75: ROYAL_ENCHANTED_LOCK
  76: NEPTUNES_ATLANTIS
  77: PINUSKI_PETAL_PURRFECT_HAVEN
  78: CANDY_LAND
  79: DRAGONS_KEEP
  80: EMERALD_CITY
  81: ANCESTRAL_PLANE
  82: BLACK_DIGITAL_RAIN
  83: SOUTH_POLE_WINTERFEST
